### ISSUE TITLE
committime exporter not connecting to internal gitea repo

### ISSUE THREAD

**Issue by jkmattatall** [dora-metrics/pelorus#1093]
### OpenShift version

4.13

### Problem description

I'm trying to connect a locally hosted OpenShift Pelorus Operator to a locally hosted Gitea instance. I've followed the steps provided in the OpenShoft Web Console [here](https://pelorus.readthedocs.io/en/latest/GettingStarted/Installation/#installing-operator). This has worked, and I am able to open the Grafana instance and view the GUI, which displays N/A on all but Deployment Frequency > Current interval > and it usually displays a small multiple of two here. 

Here is what I add to the Pelorus Operator's YAML file, with details redacted (all redacted details are confirmed correct):
```
      - app_name: committime-exporter
        enabled: true
        env_from_secrets:
          - gitea-secret
        exporter_type: committime
        source_url: <https://this.is.my.internal.gitea.link.net/organization/repository.git>
        source_ref: main
        extraEnv:
          - name: GIT_PROVIDER
            value: gitea
          - name: LOG_LEVEL
            value: DEBUG
```

Here's the secret I created with details redacted (all redacted details are confirmed correct):
```
oc create secret generic gitea-secret -n pelorus //
--from-literal=GIT_USER=<username> //
--from-literal=GIT_TOKEN=<full access token>//
--from-literal=SERVER=<https://this.is.my.internal.gitea.link.net/organization/repository.git>
```

I've tried variations with API_TOKEN, GIT_TOKEN, TOKEN, PASSWORD, as well as API_USER and USER. All have the same output/problem.

When I try to connect the committime exporter to my internal Gitea repository, the committime-exporter-1-build pod has an "Init:Error" with the following debug log:
```
Defaulted container "docker-build" out of: docker-build, git-clone (init), manage-dockerfile (init)
Error from server (BadRequest): container "docker-build" in pod "committime-exporter-1-build" is waiting to start: PodInitializing
```

When I check the Build details on the committime-exporter-1, this is always the log:
```
Cloning "https://this.is.my.internal.gitea.link.net/organization/repository.git" ...
error: failed to fetch requested repository "https://this.is.my.internal.gitea.link.net/organization/repository.git" with provided credentials
```

I am confident my username and token are correct. What could be wrong here?

### Steps to reproduce

1. Locally host OpenShift and Gitea (I understand this is not something one will reproduce).
2. Follow the steps [here](https://pelorus.readthedocs.io/en/latest/GettingStarted/Installation/#installing-operator) to install the Pelorus Operator on OpenShift.
3. Attempt to connect a committime exporter using the Pelorus Operator's YAML I provided in the description.

### Current behavior

When I try to connect the committime exporter to my internal Gitea repository, the committime-exporter-1-build pod has an "Init:Error" with the following debug log:
```
Defaulted container "docker-build" out of: docker-build, git-clone (init), manage-dockerfile (init)
Error from server (BadRequest): container "docker-build" in pod "committime-exporter-1-build" is waiting to start: PodInitializing
```

When I check the Build details on the committime-exporter-1, this is always the log:
```
Cloning "https://this.is.my.internal.gitea.link.net/organization/repository.git" ...
error: failed to fetch requested repository "https://this.is.my.internal.gitea.link.net/organization/repository.git" with provided credentials
```

### Expected behavior

I expect the Prometheus connection to Gitea to be successful and Grafana to display updates to the GUI. I expect no error logs with the committime exporter pods/builds.

### Code of Conduct

- [X] I agree to follow Pelorus's Code of Conduct

**Comment by jkmattatall** [comment]
Hi @mateusoliveira43! Thanks so much for the swift response. This appears to have worked, I now have committime/deploytime/webhook exporter pods set up and running, however I don't seem to be able to see any changes in Grafana when commits are made in the main branch in the repository. In Grafana I see these under Pelorus:

- _Software Delivery Performance_, everything here says N/A
- _Software Delivery Performance - By App_, Deployment Frequency > Current interval displays 1 for a few minutes on start, and then returns to N/A, after some more time the Application selector at the top can no longer select committime/deploytime/webhook 

How would I test that the exporters are properly connected and see changes in Grafana?

**Comment by mateusoliveira43** [comment]
I think is everything working then. Probably grafana filter was last 5 minutes when you saw, then after this time, there were no new commits to show (check now selecting a big interval, like last 2 days, the 1 commit should show there).

I suggest you read through this to understand the measures https://pelorus.readthedocs.io/en/latest/GettingStarted/QuickstartTutorial/ its an example using GitHub and GitHub issues, but  you could modify the configuration options to test with Gitea

**Comment by jkmattatall** [comment]
Thank you for the assistance again! I'm a Pelorus/metrics newbie so forgive my questions. It seems as though with just the Pelorus OpenShift Operator and the link to Gitea that it is not displaying any metrics. To me it looks like committime/deploytime in the Quickstart Tutorial you linked requires the project to be deployed in a namespace, and doesn't specifically have a link to the GitHub repository (besides the repo being what is deployed).

In your first comment:

> Can you try using this yaml and this secret?
> 
> ```yaml
>       - app_name: committime-exporter
>         enabled: true
>         env_from_secrets:
>           - gitea-secret
>         exporter_type: committime
>         extraEnv:
>           - name: GIT_PROVIDER
>             value: gitea
>           - name: LOG_LEVEL
>             value: DEBUG
> ```
> 
> ```shell
> oc create secret generic gitea-secret -n pelorus \
> --from-literal=API_USER=<username> \
> --from-literal=TOKEN=<full access token> \
> --from-literal=GIT_API=<https://this.is.my.internal.gitea.link.net/organization/repository.git>
> ```

There seems to be a link to the Gitea repo itself and not a deployed instance. Is this supposed to be strictly a link to an undeployed Gitea repository and not a deployed instance? If so, are metrics supposed to be gotten using committime/deploytime from just changes to a repo branch? If not, why does giving the exporters the Gitea repo matter?

**Comment by jkmattatall** [comment]
@mateusoliveira43 Hi again! I've come to the conclusion that I likely need a Gitea link and a deployed instance of something in that link in OpenShift in order to display statistics in Pelorus. So now I have a very basic Gitea repository with a folder and a basic deployable nginx yaml in it. My issue is that it's still not displaying in Grafana, I can't select anything on the top left drop-down despite there being a deployed a running nginx pod in the nginx namespace, and no statistics are displayed (even if I select a very long time range on the top right).

I deploy the nginx yaml in the exact same way as the Quickstart Tutorial, using _git clone_ and then _oc create_. Below is my nginx.yaml:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    app.kubernetes.io/name: nginx
  name: nginx
  namespace: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
  source:
    type: Git
    git:
      uri: https://this.is.my.internal.gitea.link.net/organization/repository.git
      ref: main
```

Here's the exporters section of my Pelorus Operator yaml:

```
  exporters:
    global: {}
    instances:
      - app_name: deploytime-exporter
        enabled: true
        env_from_secrets:
          - gitea-secret
        exporter_type: deploytime
        extraEnv:
          - name: GIT_PROVIDER
            value: gitea
          - name: LOG_LEVEL
            value: DEBUG
          - name: NAMESPACES
            value: nginx
      - app_name: committime-exporter
        enabled: true
        env_from_secrets:
          - gitea-secret
        exporter_type: committime
        extraEnv:
          - name: GIT_PROVIDER
            value: gitea
          - name: LOG_LEVEL
            value: DEBUG
          - name: NAMESPACES
            value: nginx
```

My gitea-secret is what you recommended above with API_USER/TOKEN/GIT_API, and I've confirmed those are correct. Do you have any ideas why it may not be recognizing my nginx pod in the nginx namespace?
