### ISSUE TITLE
Configure nodeSelectors via Pelorus CRD

### ISSUE THREAD

**Issue by shaprerna** [dora-metrics/pelorus#1178]
### OpenShift version

Not related to OpenShift

### Problem description

Patched pelorus sub config to add nodeSelector and Tolerations but when looking at pelorus operator pod that hasn't cascaded to the pod 

### Steps to reproduce

Adding below pelorus subscription yaml with nodeSelector and tolerations from values.yaml 

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: devworkspace-operator-fast-redhat-operators-openshift-marketplace
spec:
  config:
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 4Gi
 ```

values.yaml 

```yaml
nodeSelector:
  node-role.kubernetes.io/infra: ''
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists
```

### Current behavior

Pelorus operator pod doesn't apply above nodeSelector or Tolerations or these resource config it still has the default values.

### Expected behavior

Pelorus operator pod should be updated with nodeSelector or Tolerations and these resource config values.

### Code of Conduct

- [x] I agree to follow Pelorus's Code of Conduct
