### ISSUE TITLE
Script to create Pelorus Operator should properly tag IS, and images for exporters

### ISSUE THREAD

**Issue by mpryc** [dora-metrics/pelorus#852]
Current way of tagging Pelorus Operator and it's exporter images in our scripts is wrong.

A bit of background to capture what's where and how the scripts should be working:

1. For each exporter deployment or exporter build (referenced by the `app_name` in the instance creation) we do create corresponding `app_name` ImageStream in the Pelorus namespace, so for the:

```yaml
exporters:
  instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
    image_tag: stable

  - app_name: deploytime-notag
    exporter_type: deploytime

  - app_name: deploytime-latest
    exporter_type: deploytime
    image_tag: latest

  - app_name: deploytime-master
    exporter_type: deploytime
    source_ref: master
    source_url: https://github.com/konveyor/pelorus.git

  - app_name: deploytime-version
    exporter_type: deploytime
    image_name: quay.io/pelorus/pelorus-deploytime-exporter
    image_tag: v2.6.0
```

We will get the following image streams:
```shell
$ oc get is -n pelorus
NAME                  IMAGE REPOSITORY                                                               TAGS     UPDATED
deploytime-exporter   image-registry.openshift-image-registry.svc:5000/pelorus/deploytime-exporter   stable   10 seconds ago
deploytime-latest     image-registry.openshift-image-registry.svc:5000/pelorus/deploytime-latest     latest   10 seconds ago
deploytime-master     image-registry.openshift-image-registry.svc:5000/pelorus/deploytime-master              
deploytime-notag      image-registry.openshift-image-registry.svc:5000/pelorus/deploytime-notag      stable   10 seconds ago
deploytime-version    image-registry.openshift-image-registry.svc:5000/pelorus/deploytime-version    v2.6.0   
```

We can see that two of the ImageStreams do not have tags:
```
deploytime-master
deploytime-version
```
The first one is because the OCP is building our image from the source, and basically the source build did not finish yet. Once it finishes the `deploytime-master` will get tag `latest`, but the `deploytime-version` will not get any tag because we specified to use `v2.6.0` which is missing from our `quay.io/pelorus/pelorus-deploytime-exporter` image.

Those ImageStreams are created using helm templates (`charts/subcharts/exporters/templates`):
 - for the from the source deployment type: `_imagestream.yaml`
 - for from the image deployment type: `imagestream_from_image.yaml`

Those ImageStreams are local to the cluster and the `tags` in ImageStream are also **local** to the cluster, so we can have `stable` label referencing any quay.io tag we want.

The ImageStream part from our templates responsible for setting local tag is quite confusing and here is a stripped down version of the `imagestream_from_image.yaml` to explain what is what.

- On line number `6` we define ImageStream, which matches our `app_name`, so the `name` applies to the ImageStream.
- On line number `13` we point to the `quay.io` image with the tag of that exporter image, so the `name` is defacto an URI of the podmnan exporter image.
- On line number `14` we define an ImageStream `TAG` for that has nothing to do with the quay.io tags nor the image names. It is just  the TAG within the ImageStream local to the OCP cluster. In our case we have only one tag per ImageStream corresponding to the deployed exporter. The line number `14` can be anything, but **must** be a valid tag. This later by other charts is used to point to the local image registry as the: `app_name:TAG`, where app_name is the one from line `6` and TAG is from the line `14`. See `_deploymentconfig.yaml` example below.

```yaml
---
1  apiVersion: image.openshift.io/v1
2  kind: ImageStream
3  metadata:
4      labels:
5          app.kubernetes.io/name: {{ .app_name }}
6      name: {{ .app_name }}
7  spec:
8      lookupPolicy:
9          local: true
10    tags:
11    - from:
12        kind: DockerImage
13        name: quay.io/pelorus/pelorus-{{ .exporter_type }}-exporter:{{ .image_tag | default "v2.0.7" }}
14    name: {{ .image_tag | default "stable" }}
15    referencePolicy:
16        type: Local
{{- end }}
```

The local ImageStream is being used in our `_deploymentconfig.yaml` and the `name` must match the created ImageStream `name`. Note that for the deployment from the source defined by the `source_ref` or/and `source_url` it's :latest.

```yaml
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .app_name }}
      from:
        kind: ImageStreamTag
        {{- if or .source_ref .source_url }}
        name: {{ .app_name }}:latest
        {{- else }}
        # default is an internal registry tag and must match the default from
        # _imagestream_from_image.yaml
        name: {{ .app_name }}:{{ .image_tag | default "stable" }}
        {{- end }}
    type: ImageChange
```

So our script to create operator and modify those helm chart templates is not right atm
