### ISSUE TITLE
Define static app_name for Failure exporter

### ISSUE THREAD

**Issue by xpokor85** [dora-metrics/pelorus#994]
### Feature description

Ability to add a static definition of the app_name for the failure exporter.

The main problem is that the Jira issues do not always have a united label that we could unite them under and some Jira projects contain multiple services. Changing the Jira template is non-feasible.

We can overcome this by defining a new instance of the exporter for each service with a custom Jira query which would get only tickets that are relatable to some service and statically defining the app_name under which the tickets should be accumulated. 

Possible config snippet.
```
- app_name: psca-failure-exporter-test
        enabled: true
        exporter_type: failure
        extraEnv:
          - name: TOKEN
            value: <token>
          - name: PROVIDER
            value: jira
          - name: SERVER
            value: https://issues.redhat.com/
          - name: JIRA_JQL_SEARCH_QUERY
            value: project = PVCORE AND issuetype = Bug and EXD-Service in (product-service-config, product-service-config-auto)
          - name: LOG_LEVEL
            value: debug
          - name: APP_NAME
            value: PSCA
```

### How this will help you

It would add versatility and allow us to define Failure exporter for each service respectively.
That would unblock us from progressing the PoC and would solve a lot of Edge cases with Jira projects.

### Feature priority

🚨 As soon as possible, it block me of using Pelorus

### Code of Conduct

- [X] I agree to follow Pelorus's Code of Conduct
